1) Fixed the following warning message by added the missing argument to the sprintf function.
src/databases/VCellMTMD/ExpressionParser/ASTPowerNode.cpp: In member function ‘virtual double ASTPowerNode::evaluate(int, double*)’:
src/databases/VCellMTMD/ExpressionParser/ASTPowerNode.cpp:113: warning: too few arguments for format


2) Fixed the following message. You would think this would be an error since it can tell you are giving it bad information. The limiting size of the string argument to snprintf was wrong, it was to large for the given string, and could overflow the buffer. Changed the size to the correct size.

In function ‘int snprintf(char*, size_t, const char*, ...)’,
    inlined from ‘void vtkVisItCubeAxesActor::ComputeLabelExponent(const double*)’ at /work/camp/jason/src/avt/Plotter/vtk/vtkVisItCubeAxesActor.C:874:
/usr/include/bits/stdio2.h:66: warning: call to int __builtin___snprintf_chk(char*, long unsigned int, int, long unsigned int, const char*, ...) will always overflow destination buffer



git-svn-id: svn+ssh://portal-auth.nersc.gov/project/projectdirs/visit/svn/visit/trunk/src@16877 18c085ea-50e0-402c-830e-de6fd14e8384